import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/dist/client/image'
import capa from '../assets/capa_marvel.jpg'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marvel Comics App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.imageSection}>
          {/* Aqui vai ter umas images e um texto sobre o site -> mais um carrossel  */}
        </div>

        <div className={styles.moreCharacters}>

          <h2>Characters in more comics</h2>
        </div>
        
      </main>

    </div>
  )
}

export default Home
