import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { CharacterCard } from '../components/CharacterCard';
import { ComicCard } from '../components/ComicCard';
import { EventCard } from '../components/EventCard';
import { useCard } from '../context/CardContext';
import { Character } from '../interfaces/Character';

interface HomeProps {
  characters: Character[];
}

import styles from '../styles/Home.module.scss';
export default function Home() {
  const {
    characters,
    comics,
    series,
    getCharacters,
    getComics,
    getSeries,
    events,
    getEvents,
  } = useCard();

  useEffect(() => {
    getCharacters();
  }, []);

  // useEffect(() => {
  //   getComics();
  // }, []);
  // useEffect(() => {
  //   getEvents();
  // }, []);

  // useEffect(() => {
  //   getSeries();
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Marvel Comics App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.imageSection}>
          {/* Aqui vai ter os eventos -> mais um carrossel  */}
          {events.map((event) => {
            return <EventCard key={event.id} event={event} />;
          })}
        </div>

        <div className={styles.cardsContainer}>
          <h2>Characters in more comics</h2>

          <div className={styles.cardGroup}>
            {characters.map((character) => {
              return <CharacterCard key={character.id} character={character} />;
            })}
          </div>
        </div>

        <div className={styles.cardsContainer}>
          <h2>Comics</h2>

          <div className={styles.cardGroup}>
            {/* {comics.map((comic) => {
              return <ComicCard key={comic.id} comic={comic} />;
            })} */}
          </div>
        </div>

        <div className={styles.cardsContainer}>
          <h2>Some Series</h2>

          {/* <div className={styles.cardGroup}>
            <CharacterCard />
            <CharacterCard />
            <CharacterCard />
            <CharacterCard />
            <CharacterCard />
            <CharacterCard />
          </div> */}
        </div>
      </main>
    </div>
  );
}

// export const getStaticProps: GetStaticProps = async () => {
//   const res = await fetch(
//     `https://gateway.marvel.com/v1/public/characters?ts=${time}&apikey=${apiKey}&hash=${hash}`,
//   );
//   const json = await res.json();

//   const characters: Character[] = json.data.results.map(
//     (character: Character) => {
//       return {
//         id: character.id,
//         name: character.name,
//         description: character.description,
//         thumbnail: character.thumbnail,
//         comics: character.comics,
//         series: character.series,
//         stories: character.stories,
//         url: character.url,
//       };
//     },
//   );

//   return {
//     props: {
//       characters,
//     },
//     revalidate: 60 * 60 * 8, //8 hrs
//   };
// };
